### ISSUE TITLE
Charset utf-8

### ISSUE THREAD

**Issue by 95Key** [fbdesignpro/sweetviz#26]
First of all it’s awesome! Many thanks for your effort on data visualization! There is a small issue maybe, the html report lacks a meta tag showing the charset as “utf-8”; by adding it, the report can correctly show the MBCS characters and will catch eyes of more global analysts.
Thanks again! Hope this project goes better!

**Comment by davebulaval** [comment]
Same problem with French dataset no UTF-8 support.

**Comment by fbdesignpro** [comment]
@95Key @davebulaval thank you for submitting this! I was not able to respond for the past few days but we are testing #33 which should fix this, we will keep you posted!

**Comment by a246530** [comment]
@95Key or @davebulaval  , can you give me a copy of the dataset to check that this is fixed? i havent run into an issue with the encoding but added the meta tag per this request. 
I downloaded a dataset with french in it and all chars displayed fine without the UTF-8 meta tag.

**Comment by 95Key** [comment]
@a246530  Thank you for your prompt reply,  I prepared a test file and hope to help you :)
[stock_basic.csv.zip](https://github.com/fbdesignpro/sweetviz/files/4928990/stock_basic.csv.zip)

**Comment by fbdesignpro** [comment]
@95Key thank you for the sample data, and @a246530 for checking it out; hopefully it fixes it!

**Comment by a246530** [comment]
@fbdesignpro , i just tested this. It will show correct characters with the UTF-8 meta tag. It will not show them without it.

**Comment by fbdesignpro** [comment]
(Weird, I think the response just wrote disappeared? Writing it up again...) @a246530 it seems to be working but:
-Getting lots of warnings regarding missing glyphs during report generation
-Graphs will show a missing character symbol

This is due to CJK not being included in the fonts but I can work around that in an upcoming fix. For now I will probably just use your fix with text output. I just wanted to confirm this is the behavior you are seeing also. Thanks!

**Comment by a246530** [comment]
Correct. I had missing glyphs errors as well.

**Comment by fbdesignpro** [comment]
Should be closed by 7c3a754. 

STILL warnings + missing characters in graphs; It's on my to-do list :)
