### ISSUE TITLE
Data type issue

### ISSUE THREAD

**Issue by v-rao** [fbdesignpro/sweetviz#3]
TypeError: Column InvoiceNo has a 'mixed' inferred_type (as determined by Pandas). This is is not currently supported; column types should not contain mixed data. e.g. only float, or strings, but not a combination.

**Comment by fbdesignpro** [comment]
Hi! Thank you for the report! This is as the message described; Pandas is reporting a mixed type and the system is unsure how to handle it. This is a bit of an incentive to clean up the data so it is clearly numerical, categorical or plain text.

I COULD have the system treat such a case as "text", but I feel having this message forces the user to make a choice helps.

I could also try to get the detection to work better, and/or have the error message be more explicit.

What type of data are you using, and what would be the expected behavior? This is an interesting issue and I am curious to hear anyone's feedback also.

Francois

**Comment by fbdesignpro** [comment]
In the meantime, looking into it, I will at least add a lot more info to the error message.

**Comment by v-rao** [comment]
@fbdesignpro 

I was working on the online retail dataset. 

![Screenshot (597)](https://user-images.githubusercontent.com/40270731/84234812-78a40e80-ab12-11ea-969e-8c56324748b2.png)

In this dataset, the variable 'Invoice Number' is a 6-digit integral number uniquely assigned to each transaction. If this code starts with the letter 'C', it indicates a Cancellation. 

And once I run the following code I get the error below:

![Screenshot (598)](https://user-images.githubusercontent.com/40270731/84235442-7bebca00-ab13-11ea-8c25-754f57b4ff34.png)
