### ISSUE TITLE
Issue when running show_html() method

### ISSUE THREAD

**Issue by tzoukritzou** [fbdesignpro/sweetviz#63]
I tried the basic usage with an = sv.analyze(df) and then an.show_html(). Then I get the error:

Traceback (most recent call last):
  File "yo.py", line 27, in <module>
    an.show_html()
  File "/usr/local/lib/python3.8/dist-packages/sweetviz/dataframe_report.py", line 276, in show_html
    self._page_html = sv_html.generate_html_dataframe_page(self)
  File "/usr/local/lib/python3.8/dist-packages/sweetviz/sv_html.py", line 64, in generate_html_dataframe_page
    output = template.render(dataframe=dataframe_report)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/dist-packages/sweetviz/templates/dataframe_page.html", line 47, in top-level template code
    span.association-graph-source::before { content: url(data:image/png;base64,{{ dataframe._association_graphs.all.graph_base64.decode('ascii') }});}
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'all'

**Comment by fbdesignpro** [comment]
Hello @tzoukritzou, thank you so much for the report! This is a strange error... Is there anything you can tell me regarding the data you are using? Or any parameters like are you using any options like turning off pairwise_analysis?

 Thanks again!

**Comment by tzoukritzou** [comment]
Hi @fbdesignpro. Nothing out of the ordinary with my data I suppose, the df is a dataframe with around 20000 rows and 800 columns. Only numbers in the data, no categorical features, no na values. I am not using any parameters in the function calls so the defaults are used.

I just tried running it with pairwise_analysis='off'. First, while before it took 2 seconds to finish, with this parameter specified it took 15 minutes. But it worked, the report was generated succesfully with this parameter specified.

**Comment by fbdesignpro** [comment]
@tzoukritzou thank you for the info! Yes 800 columns would take a long time since it's roughly (n^2) combinations to compute. Not sure why that would make it failed in such a weird way, though.

I do have 2 quick questions:

1. Did you get a warning initially about needing to explicitly set `pairwise_analysis='on'`? I'm asking just to make sure the system works as intended (for such a large number of columns it should be asking you to be explicitly turning it on)

2. Have you tried with only, like let's say 3 rows (instead of 20,000)? It will take some time due to the exponential number of combinations, but should be much shorter to generate and will tell us if it could be related to memory usage or something like that.

Thanks again!
Francois
