### ISSUE TITLE
the target rate samll than 0.01% not show on the report

### ISSUE THREAD

**Issue by haiyuni** [fbdesignpro/sweetviz#72]
the target rate is 0.0004% in my data, I user the sweetviz packages,but it's not show the target rate in my analysi report

**Comment by fbdesignpro** [comment]
Hello @haiyuni! Thank you for your reports and apologies for the delay in answering (it's been a crazy month!). That is a very low occurrence rate and probably gets rounded down... that's a good catch I will look into it for the next revision! Thank you again!

**Comment by haiyuni** [comment]
thanks,This is a great package

**Comment by fbdesignpro** [comment]
Hello again @haiyuni! Just for clarity, this issue here about "not showing on the report", is this also related to the scale of the graph? Or is this in another section of the report? I'm only asking because I did a few tests with 0.0004% positive, and it does show up. I mean the absolute numbers are correct, but the percentages are rounded down to 0% so I wanted to know if this is what you were asking about for issue #72.

**Comment by haiyuni** [comment]
sorrry ，it's shuld  be the target rate is round 0 in the TOP CATEGORIES  report.

**Comment by fbdesignpro** [comment]
Hello @haiyuni ! I just pushed version 2.0.7 which will display "<1%" and similar notations instead of just "0%" (in a couple of places). There is not room to show much more, but I think it's already a big improvement. Thank you again! The definitely let me know if you are able to update and see this and it works properly. :)
