### ISSUE TITLE
Add number and prct of negative values to feature information 

### ISSUE THREAD

**Issue by gverbock** [fbdesignpro/sweetviz#78]
I would like to create a PR for adding the number of negative values to the base statistics. In addition, if I am right, the number of zeroes is also not displayed. 

The output of the implementation would look like this:

![image](https://user-images.githubusercontent.com/32060943/108907918-04b78100-7623-11eb-8451-e28d0e3c7847.png)

**Comment by fbdesignpro** [comment]
Hello @gverbock, thank you for the detailed PR! 

I actually toyed with this initially (at least, the zeros), but favored the "design/cleanliness/readability" of having the left section be common to all data types (i.e. text, categorical and numerical variables all share values/missing/distinct), and have some room.

I want to remain cognizant of the importance of keeping readability because value/missing/distinct are critical values, shared by all data types.

I'm sure you're not the only one who would like to see zeros, so I could add it pretty easily below "distinct" for numerical data. Negative may or may not be significant for all numerical features.

Another alternative could be to add it to the detail area, perhaps below "missing".

**Comment by fbdesignpro** [comment]
Just noticing that "zeros" has been requested for a while (#44), so I will add it as described above. :)

**Comment by gverbock** [comment]
Dear @fbdesignpro. 

Great you will add the statistics on thee zeroes to sweetviz.

**Comment by fbdesignpro** [comment]
Hi @gverbock, I just committed 2.0.9, which adds "zeroes" count! After thinking about it, for now I won't implement negative numbers, however, to avoid overcrowding the display. If I get lots of requests I will look into adding it perhaps as an option.

Either way, thank you for pushing for that feature, I think everyone will benefit!
