### ISSUE TITLE
How to display HTML page of sweetviz library after it uploaded on Github 

### ISSUE THREAD

**Issue by YASHGUPTA2611** [fbdesignpro/sweetviz#93]
After visualization, I uploaded Sweetviz Visualization HTML pages on my Github repo, but if i am opening the HTLM file it is showing the source code.
How can i see the html  page within the Github.

**Comment by fbdesignpro** [comment]
Hi @YASHGUPTA2611 I believe this is due to how Github stores/displays pages.

Are you able to display any other HTML file?

If not, it does feel like that's a built-in design for Github. This stack overflow thread seems to have good workarounds and discussions on the topic:

https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview

**Comment by YASHGUPTA2611** [comment]
@fbdesignpro Thank you for the solution. 

You can see any Github HTML page on this link - [https://htmlpreview.github.io/(path_to_the_html_page_on_the_repo)](url)

**Comment by fbdesignpro** [comment]
@YASHGUPTA2611 Awesome! I'm glad you're able to get the answer! :)
