### ISSUE TITLE
Analyze fails on the file with large number of columns

### ISSUE THREAD

**Issue by tricision** [fbdesignpro/sweetviz#98]
This is a great tool, but recenetly I ran into an issue analyzing a file with over 200 columns.  I only have about 80,000 rows, so the file is not huge.

The code is very simple(see below).  I can attach sample file if that helps.

When I run it interacrtively it just stops executing.  From command line I get "Fail to allocate bitmap" error. Traceback is attached
[Traceback.txt](https://github.com/fbdesignpro/sweetviz/files/6971804/Traceback.txt)

_import sweetviz as sv
import pandas as pd

df = pd.read_csv('C:/temp/test.csv', sep=',', header=0);

report = sv.analyze(df,pairwise_analysis='Off');

report.show_html(filepath='C:/temp/Comparison.html')_

**Comment by fbdesignpro** [comment]
Hi @tricision! Thank you for the detailed report!

It looks like the issue is not related to Sweetviz or the number of columns (I have run it with many more), as the traceback is pointing towards an issue encoding Unicode character 2070 ("superscript zero") during **import**!!

Looking online, it looks like updating/reinstalling numpy (or even conda?) would solve the issue:

https://github.com/numpy/numpy/issues/7783
https://forum.knime.com/t/unicodeencodeerror-when-import-numpy-in-scripting-node/11870

Thanks again, and I hope this helps!
